services:
  workspace-host:
    build:
      context: repos/images/platform/workspace-host
      dockerfile: Dockerfile
    container_name: limespaces-workspace-host
    privileged: true
    volumes:
      - ./run/limespaces:/limespaces # docker socket
      # Volumes to fix daemon failures (mounting into overlayfs)
      - limespaces-workspace-host-docker:/var/lib/docker
      - limespaces-workspace-host-containerd:/var/lib/containerd
      - limespaces-workspace-host-sysbox:/var/lib/sysbox

  orchestrator:
    tty: true
    build:
      context: .
      dockerfile: repos/images/platform/orchestrator/dev.Dockerfile
    container_name: limespaces-orchestrator
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/app/repos/orchestrator/node_modules"
      - "/app/repos/orchestrator/dist"
      - "/app/repos/shared/node_modules"

      - "./run/limespaces:/var/run/limespaces:ro"
    ports:
      - "3001:3000"
    env_file:
      - ./env/orchestrator.env

  dashboard:
    tty: true
    build:
      context: .
      dockerfile: repos/images/platform/dashboard/dev.Dockerfile
    container_name: limespaces-dashboard
    volumes:
      - ".:/app"
      - "/app/node_modules"
      - "/app/repos/dashboard/node_modules"
      - "/app/repos/dashboard/.next"
      - "/app/repos/shared/node_modules"
    ports:
      - "3000:3000"
    env_file:
      - ./env/dashboard.env

  postgres:
    image: postgres:18
    container_name: limespaces-postgres
    env_file:
      - ./env/postgres.env
    volumes:
      - ./var/postgres:/var/lib/postgresql

  redis:
    image: redis:8.8
    container_name: limespaces-redis
    volumes:
      - ./var/redis:/data
    env_file:
      - ./env/redis.env

  registry:
    image: registry:2
    container_name: limespaces-registry
    ports:
      - "5001:5000"
    volumes:
      - ./var/registry:/var/lib/registry

volumes:
  limespaces-workspace-host-docker:
  limespaces-workspace-host-containerd:
  limespaces-workspace-host-sysbox:
